name: Lint Commit Messages
on: [pull_request]

permissions:
  pull-requests: write
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        id: commitlint
      - if: ${{ failure() && steps.commitlint.outcome == 'failure' }}
        uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
        with:
          header: Commitlint
          recreate: true
          message: |
            Activate local hooks please
      - if: ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
        with:
          header: Commitlint
          delete: true
